name: all_universe_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 响应式适配
  flutter_screenutil: ^5.6.0

  # ios 图标库
  cupertino_icons: ^1.0.2

  # getx
  get: ^4.1.4

  # 日期格式
  intl: ^0.17.0

  # loaing
  flutter_easyloading: ^3.0.0

  # http
  dio: ^4.0.0
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0

  # storage + cache
  shared_preferences: ^2.0.6
  cached_network_image: ^3.0.0

  # 上拉刷新/下拉加载
  pull_to_refresh: ^2.0.0

  # webview
  webview_flutter: ^4.0.7

  # 拍照/图片 相关
  image_picker: ^0.7.5+3
  permission_handler: ^8.0.0+2
  photo_view: ^0.11.1
  image_gallery_saver: ^1.6.9
  flutter_cache_manager: ^3.1.0
  
  # 音频播放
  just_audio: ^0.9.31
  just_audio_background: ^0.0.1-beta.9

  #底部弹框
  modal_bottom_sheet: ^3.0.0-pre

  #震动
  vibration: ^1.7.6
  
dev_dependencies:
  #logo生成 flutter pub run flutter_launcher_icons
  flutter_launcher_icons: ^0.13.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - lib/assets/images/
   - lib/assets/lottie/
   - lib/assets/images/tabbar/
   - lib/assets/lottie/lottie_list_pull_refresh.json
   - lib/assets/images/player/
   - lib/assets/images/common/ 
   - lib/assets/images/home/
   - lib/assets/images/cover/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/common/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/assets/images/common/logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "lib/assets/images/common/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "lib/assets/images/common/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "lib/assets/images/common/logo.png"